### ISSUE TITLE
Lazy not supported

### ISSUE THREAD

**Issue by Heziode** [cressie176/yup-by-example#4]
**Describe the bug**

It throw an error when the schema contains a Lazy input:

```
[2021-08-07T13:41:09.587Z] error TypeError: Cannot read property 'filter' of undefined
    at /srv/app/node_modules/yup-by-example/src/yup-by-example.js:41:8
    at Array.forEach (<anonymous>)
    at describe (/srv/app/node_modules/yup-by-example/src/yup-by-example.js:36:36)
    at ObjectSchema.yupByExample (/srv/app/node_modules/yup-by-example/src/yup-by-example.js:21:15)
    at /srv/app/node_modules/yup/lib/schema.js:197:94
    at Array.reduce (<anonymous>)
    at ObjectSchema._cast (/srv/app/node_modules/yup/lib/schema.js:197:69)
    at ObjectSchema._cast (/srv/app/node_modules/yup/lib/object.js:82:23)
    at ObjectSchema.cast (/srv/app/node_modules/yup/lib/schema.js:185:33)
    at ObjectSchema._cast (/srv/app/node_modules/yup/lib/object.js:125:15)
    at ObjectSchema.cast (/srv/app/node_modules/yup/lib/schema.js:185:33)
    at /srv/app/node_modules/yup/lib/array.js:66:42
    at Array.map (<anonymous>)
    at ArraySchema._cast (/srv/app/node_modules/yup/lib/array.js:65:29)
    at ArraySchema.cast (/srv/app/node_modules/yup/lib/schema.js:185:33)
    at ObjectSchema._cast (/srv/app/node_modules/yup/lib/object.js:125:15)
```

**To Reproduce**
**Minimal** steps to reproduce the behavior, ideally including a well formatted code snippet or link to a gist.

```js
const yup = require('yup');
const yupByExample = require('yup-by-example');
const { mapValues } = require("lodash");

const customFieldsSchema = yup.lazy(map => yup.object(
  mapValues(map, (_, key) => {
    return yup.object({
      key: yup.string().oneOf([key]).min(1).max(30).required(mixedYup.required).example(),
      placeholder: yup.string().min(0).max(30).example(),
      show: yup.boolean(mixedYup.notType).required(mixedYup.required).example(),
      value: yup.string().min(0).max(30).example(),
    }).example();
  })
).example());

const formSchema = yup.object({
  customFields: customFieldsSchema,
  message: yup.string().min(1).max(100).example(),
}).example();

const schemaExample = await yupByExample.TestDataFactory.init().generateValid(formSchema);
```

**Expected behavior**

Generate a valid example.

**Desktop (please complete the following information):**
 - OS: Linux 5.10.25-linuxkit (Docker)
 - Node / Browser version: node 12.20.1
 - Library Version: 3.1.2

**Additional context**

I think this case is just missing. However, since lazy is… lazy, it could be difficult to support it. Maybe add a way to generate some "Lazy" fields during generation

**Comment by cressie176** [comment]
Hi @Heziode,

Thanks for the bug report. At the very least we should either report a better error, or potentially suppress it so a partially valid document could be generated. I'll have to dig into the internals of yup's lazy implementation to see if we can properly support though.

**Comment by cressie176** [comment]
Three years late. yup-by-example no longer crashes when it encounters a lazy schema. I can't see a way to generate values though. Will release to npm shortly
